#!/bin/sh

location=$(awk -F'"' '/location *=/ {print $2}' ~/.config/chezmoi/chezmoi.toml)
if [ "$location" == "clip" ]; then
   exit
fi

if [ -d ~/.powerlevel10k ]; then
    cd ~/.powerlevel10k
    git pull >/dev/null
else
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.powerlevel10k >/dev/null
fi
