#!/bin/bash 
#
# Get user certificate and ssh-keys from Bitwarden

set -eo pipefail

# skip if Bitwarden is not unlocked
[[ -z "$BW_SESSION" ]] && exit

# skip if certificate exists
[[ -e ~/.globus/usercert.pem ]] && exit 

status="$(bw status | jq -r ".status")"
[[ $status != "unlocked" ]] && exit

folderid="$(bw list folders --search certificates | jq -er ".[0].id")"
itemid="$(bw list items --search grid --folderid "$folderid" | jq -re ".[0].id")"

bw get attachment usercert.pem --itemid="$itemid" --output ~/.globus/usercert.pem >/dev/null
bw get attachment userkey.pem --itemid="$itemid" --output ~/.globus/userkey.pem >/dev/null
chmod 600 ~/.globus/userkey.pem
